use universidad ;
use tienda;
/*TIENDA*/ 
/* 1 */SELECT nombre FROM tienda.producto;
/* 2 */SELECT nombre,precio FROM tienda.producto;
/* 3 */SELECT * FROM tienda.producto;
/* 4 */SELECT nombre,precio , precio * 1.07 FROM tienda.producto;
/* 5 */SELECT nombre,precio AS Euro, precio * 1.07 AS Dolar FROM tienda.producto;
/* 6 */SELECT UPPER(nombre),UPPER(precio)FROM tienda.producto;
/* 7 */SELECT LOWER(nombre),LOWER(precio)FROM tienda.producto;
/* 8 */SELECT nombre,UPPER(LEFT(nombre,2)) AS dos_letras FROM tienda.fabricante;
/* 9 */SELECT nombre,precio,ROUND(precio) AS precio_redondeado FROM tienda.producto;
/* 10 */SELECT nombre,precio,TRUNCATE(precio,0) AS truncado FROM tienda.producto;
/* 11 */SELECT fabricante.codigo FROM tienda.fabricante JOIN tienda.producto ON fabricante.codigo = producto.codigo_fabricante;
/* 12 */SELECT DISTINCT fabricante.codigo FROM tienda.fabricante JOIN tienda.producto ON fabricante.codigo = producto.codigo_fabricante;
/* 13 */SELECT nombre FROM tienda.fabricante ORDER BY nombre ASC;
/* 14 */SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
/* 15 */SELECT nombre FROM producto ORDER BY nombre,precio DESC;
/* 16 */SELECT * FROM fabricante LIMIT 5;
/* 17 */SELECT * FROM fabricante LIMIT 3,2;
/* 18 */SELECT nombre,precio FROM producto ORDER BY precio  LIMIT 1;
/* 19 */SELECT nombre,precio FROM producto ORDER BY precio DESC  LIMIT 1;
/* 20 */SELECT nombre,codigo FROM fabricante WHERE codigo = '2';
/* 21 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante FROM fabricante fa JOIN producto pro ON fa.codigo = pro.codigo_fabricante;
/* 22 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM fabricante fa JOIN producto pro ON fa.codigo = pro.codigo_fabricante ORDER BY fa.nombre;
/* 23 */SELECT pro.codigo,pro.nombre AS producto,fa.codigo,fa.nombre AS fabricante   FROM fabricante fa JOIN producto pro ON fa.codigo = pro.codigo_fabricante;
/* 24 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante ORDER BY precio  LIMIT 1;
/* 25 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante ORDER BY precio DESC  LIMIT 1;
/* 26 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre = 'lenovo'; 
/* 27 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre = 'crucial' AND precio > 200; 
/* 28 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre = 'asus' OR fa.nombre = 'hewlett-packard' OR fa.nombre = 'seagate';
/* 29 */SELECT pro.nombre AS producto ,precio,fa.nombre AS fabricante  FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre IN ('asus','hewlett-packard','seagate');
/* 30 */SELECT pro.nombre,precio FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre LIKE '%e';
/* 31 */SELECT pro.nombre,precio FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre LIKE '%w%';
/* 32 */SELECT pro.nombre AS producto ,precio,fa.nombre FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE precio >= 180 ORDER BY precio DESC,pro.nombre;
/* 33 */SELECT DISTINCT fa.codigo,fa.nombre AS fabricante   FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante;
/* 34 */SELECT fa.codigo,fa.nombre AS fabricante ,pro.nombre AS producto FROM producto pro RIGHT JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante;
/* 35 */SELECT fa.codigo,fa.nombre AS fabricante ,pro.nombre AS producto FROM producto pro RIGHT JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE pro.nombre IS NULL;
/* 36 */SELECT * FROM producto pro WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = pro.codigo_fabricante AND nombre = 'lenovo');
/* 37 */SELECT * FROM producto pro WHERE precio =(SELECT precio FROM producto pro WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = pro.codigo_fabricante AND nombre = 'lenovo')ORDER BY precio DESC LIMIT 1);
/* 38 */SELECT pro.nombre AS producto FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre = 'lenovo' ORDER BY precio DESC LIMIT 1 ;
/* 39 */SELECT pro.nombre AS producto FROM producto pro JOIN fabricante fa ON fa.codigo = pro.codigo_fabricante WHERE fa.nombre = 'Hewlett-Packard' ORDER BY precio  LIMIT 1 ;
/* 40 */SELECT * FROM producto pro WHERE precio >=(SELECT precio FROM producto pro WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = pro.codigo_fabricante AND nombre = 'lenovo')ORDER BY precio DESC LIMIT 1);
/* 41 */SELECT * FROM producto pro WHERE  codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = pro.codigo_fabricante AND nombre = 'asus') AND precio >=(SELECT AVG(precio) FROM producto pro WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = pro.codigo_fabricante AND nombre = 'asus'));

/*Universidad*/
/* 1 */SELECT apellido1,apellido2,nombre FROM persona WHERE tipo = 'alumno' ORDER BY apellido1,apellido2,nombre;
/* 2 */SELECT nombre,apellido1,apellido2,telefono FROM persona WHERE tipo = 'alumno' AND telefono IS NULL;
/* 3 */SELECT * FROM persona  WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
/* 4 */SELECT * FROM persona  WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K';
/* 5 */SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
/* 6 */SELECT apellido1,apellido2,up.nombre,ud.nombre FROM persona up JOIN profesor pr ON up.id = pr.id_profesor JOIN departamento ud ON ud.id = pr.id_departamento   WHERE tipo = 'profesor' ORDER BY apellido1,apellido2,up.nombre;
/* 7 */SELECT ua.nombre,anyo_inicio,anyo_fin FROM persona up JOIN alumno_se_matricula_asignatura aa ON up.id = aa.id_alumno JOIN curso_escolar ce ON aa.id_curso_escolar = ce.id JOIN asignatura ua ON aa.id_asignatura = ua.id   WHERE nif = '26902806M';
/* 8 */SELECT DISTINCT ud.nombre FROM departamento ud JOIN  profesor up ON ud.id = up.id_departamento JOIN asignatura ua USING (id_profesor) JOIN grado ug ON ug.id = ua.id_grado WHERE ug.id = 4; 
/* 9 */SELECT DISTINCT up.* FROM persona up JOIN alumno_se_matricula_asignatura aa ON up.id = aa.id_alumno JOIN curso_escolar uc ON aa.id_curso_escolar = uc.id WHERE tipo = 'alumno' AND uc.id = 5;
/*LEFT AND RIGHT JOIN */
/* 1 */SELECT depa.nombre,apellido1,apellido2,per.nombre FROM departamento depa RIGHT JOIN profesor pro ON pro.id_departamento = depa.id  JOIN persona per ON pro.id_profesor = per.id WHERE tipo = 'profesor'  ORDER BY depa.nombre,apellido1,apellido2,per.nombre ;
/* 2 */SELECT depa.nombre,per.* FROM departamento depa RIGHT JOIN profesor pro ON pro.id_departamento = depa.id  RIGHT JOIN persona per ON pro.id_profesor = per.id WHERE depa.id IS NULL AND tipo = 'profesor' ;
/* 3 */SELECT depa.nombre,per.* FROM persona per JOIN profesor pro ON pro.id_profesor = per.id   RIGHT JOIN departamento depa ON depa.id = pro.id_departamento WHERE pro.id_profesor IS NULL;
/* 4 */SELECT per.*,asi.nombre FROM persona per JOIN profesor pro ON pro.id_profesor = per.id LEFT JOIN asignatura asi ON pro.id_profesor = asi.id_profesor WHERE asi.nombre IS NULL;
/* 5 */SELECT asi.nombre,pro.id_profesor FROM asignatura asi LEFT JOIN profesor pro ON asi.id_profesor = pro.id_profesor  WHERE pro.id_profesor IS NULL;
/* 6 */SELECT depa.nombre FROM departamento depa LEFT JOIN profesor pro ON depa.id = pro.id_profesor LEFT JOIN asignatura asi ON pro.id_profesor = asi.id_profesor LEFT JOIN alumno_se_matricula_asignatura aa ON asi.id = aa.id_asignatura WHERE aa.id_curso_escolar IS NULL GROUP BY depa.nombre;
/* Resumen */
/* 1 */SELECT COUNT(id) AS Alumnos FROM persona WHERE tipo = 'alumno';
/* 2 */SELECT COUNT(fecha_nacimiento) FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999/01/01'  AND '1999-12-31';
/* 3 */SELECT nombre,COUNT(id_profesor)  FROM departamento depa JOIN profesor pro ON  depa.id = pro.id_departamento GROUP BY nombre ORDER BY COUNT(id_profesor) DESC;
/* 4 */SELECT nombre,COUNT(id_profesor) FROM departamento depa LEFT JOIN profesor pro ON depa.id = pro.id_departamento GROUP BY Nombre;
/* 5 */SELECT gr.nombre,COUNT(asi.id) AS num_asignatura FROM grado gr LEFT JOIN asignatura asi ON gr.id = asi.id_grado GROUP BY gr.nombre ORDER BY COUNT(asi.id) DESC;
/* 6 */SELECT gr.nombre,COUNT(asi.id) AS num_asignatura FROM grado gr JOIN asignatura asi ON gr.id = asi.id_grado GROUP BY gr.nombre HAVING num_asignatura > 40;
/* 7 */SELECT gr.nombre,tipo,SUM(creditos) AS Total_de_creditos FROM grado gr JOIN asignatura asi ON gr.id = asi.id_grado GROUP BY gr.nombre,tipo;
/* 8 */SELECT anyo_inicio,COUNT(id_alumno) FROM curso_escolar ce LEFT JOIN alumno_se_matricula_asignatura aa ON ce.id = aa.id_curso_escolar GROUP BY id;
/* 9 */SELECT per.id,per.nombre,apellido1,apellido2,COUNT(asi.id) AS numero_de_asignaturas FROM profesor pro LEFT JOIN asignatura asi USING (id_profesor) LEFT JOIN persona per ON pro.id_profesor = per.id WHERE per.tipo = 'profesor' GROUP BY id_profesor ORDER BY numero_de_asignaturas DESC ;
/* 10 */SELECT * FROM persona per WHERE tipo = 'alumno' ORDER BY fecha_nacimiento DESC LIMIT 1;
/* 11 */SELECT per.nombre,apellido1,apellido2,asi.nombre AS asignaturas FROM asignatura asi JOIN profesor pro USING (id_profesor) RIGHT JOIN persona per ON pro.id_profesor = per.id WHERE asi.id IS NULL AND per.tipo = 'profesor';